# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Everton Boni - Front End Developer
email: evertonboni.fe@gmail.com
description: Desenvolvedor Front End - Espirito Santo - Brasil
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evertonboni.com.br" # the base hostname & protocol for your site
twitter_username: evertonboni
github_username:  evertontatu
linkedin_username: everton-boni-92ab7553
behance_username: evertonboni

# Build settings
markdown: kramdown

permalink: /:title

port: 8080

# exclude my node related stuff
exclude: ['package.json', 'node_modules']
